domains:
- 1337x.to
- 4chan.org
- 8kun.top
- adultfriendfinder.com
- armslist.com
- bestgore.com
- bitcoinlaundry.com
- cam4.com
- ccmarket.com
- chatroulette.com
- chaturbate.com
- deepwebmarket.com
- dreammarket.onion
- drugs-forum.com
- erome.com
- fetlife.com
- fmovies.to
- freerutor.org
- gunbroker.com
- hydraruzxpnew4af.onion
- limeTorrents.info
- livejasmin.com
- liveleak.com
- motherless.com
- omegle.com
- pornhub.com
- primewire.ag
- putlocker.is
- rarbg.to
- redtube.com
- silkroad7rn2puhj.onion
- soap2day.to
- solarmovie.to
- stripchat.com
- thepiratebay.org
- tinychat.com
- watchseries.to
- xhamster.com
- xnxx.com
- xvideos.com
- youporn.com
- yts.mx
- zoosk.com
keywords:
- adult
- adware
- anorexia
- bdsm
- bestiality
- botnet
- bulimia
- camgirl
- cams
- childporn
- cocaine
- counterfeit
- cp
- crack
- darkweb
- deepfake
- drugs
- escort
- exploit
- extremism
- fakeid
- fetish
- firearms
- forgery
- fraud
- gambling
- gore
- guns
- hatecrime
- hentai
- heroin
- hitman
- humantrafficking
- illegal
- incest
- killmyself
- lsd
- malware
- marijuana
- meth
- moneylaundering
- nazi
- nude
- organtrade
- phishing
- piracy
- porn
- racism
- ransomware
- rape
- scam
- selfharm
- sex
- snuff
- spyware
- suicide
- terror
- terrorism
- torture
- trafficking
- virus
- weed
- xxx
- zoophilia
