 
# Palavras-chave proibidas
keywords:
  - adult
  - gambling
  - piracy
  - porn
  - spyware
  - virus
  - malware
  - adware

# Domínios bloqueados
domains:
  - pornhub.com
  - xvideos.com
  - adultfriendfinder.com
  - xhamster.com
  
